services:
  ollama:
    image: ollama/ollama:rocm
    container_name: OpenRemote_Ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_CONFIG=/root/.ollama/config.json

    # Uncomment for AMD GPUs
#     devices:
#       - /dev/kfd
#       - /dev/dri

    # Uncomment for Nvidia GPUs
    deploy:
     resources:
       reservations:
         devices:
           - capabilities: [gpu]

volumes:
  ollama: